global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "todo-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:3000"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]
