{
 "title": "Todo API Monitoring",
 "panels": [
  {
   "title": "P95 HTTP Latency",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "P99 HTTP Latency",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Req/sec & Errors",
   "type": "graph",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[1m]))",
     "legendFormat": "reqs/sec"
    },
    {
     "expr": "sum(rate(http_request_errors_total[1m]))",
     "legendFormat": "errors/sec"
    }
   ]
  }
 ]
}